routes/admin.php
<?php

use App\Http\Controllers\admin\ChildProductController;
use App\Http\Controllers\admin\CmsController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\admin\LoginController;
use App\Http\Controllers\admin\UserController;
use App\Http\Controllers\admin\ManufacturerController;
use App\Http\Controllers\admin\ParentProductController;
use App\Http\Controllers\admin\SupplierController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'admin.', 'middleware' => ['guest:admin']], function () {

    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('custom-login', 'LoginController@customLogin')->name('custom-login');
    Route::get('forget-password', 'LoginController@forgetPasswordPage')->name('forget-password');
    Route::post('forget-mail-send', 'LoginController@forgetPasswordMailsend')->name('forget-mail-send');
    Route::get('adminrecover-password/{email}', 'LoginController@adminrecoverPasswordPage')->name('adminrecover-password');
    Route::post('recover-password-store', 'LoginController@recoverPasswordStore')->name('recover-password-store');

    Route::group(['middleware' => ['auth:admin', 'XSS', 'guest']], function () {
        Route::controller(LoginController::class)->group(function () {
            Route::get('user-edit', 'editPage')->name('user-edit');
            Route::post('update-profile', 'updateAdmin')->name('update-profile');
            Route::post('change-password', 'changePassword')->name('change-password');
            Route::get('logout', 'logout')->name('logout');
        });

        Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');

        Route::controller(UserController::class)->group(function () {
            Route::get('user-add', 'addUser')->name('user-add');
            Route::get('user-list', 'list')->name('user-list');
            Route::delete('user-delete', 'deleteUser')->name('user-delete');
            Route::post('user-create', 'createUser')->name('user-create');
            Route::get('user-edit-page/{id}', 'userEditPage')->name('user-edit-page');
            Route::get('user-view/{id}', 'userDetails')->name('user-view');
            Route::post('get-city','getCity')->name('get-city');
            Route::post('user-enable-disable','userEnableDisable')->name('user-enable-disable');
            Route::get('test','test')->name('test');
        });

        Route::controller(ManufacturerController::class)->group(function () {
            Route::get('manufacturer-list', 'list')->name('manufacturer-list');
            Route::get('manufacturer-add', 'addManufacturer')->name('manufacturer-add');
            Route::post('manufacturer-create', 'manufacturerCreate')->name('manufacturer-create');
            Route::get('manufacturer-view/{id}', 'manufacturerView')->name('manufacturer-view');
            Route::get('manufacturer-edit/{id}', 'manufacturerEdit')->name('manufacturer-edit');
            Route::delete('manufacture-delete', 'deleteManufacturer')->name('manufacture-delete');
            Route::post('manufacturer-enable-disable','manufacturerEnableDisable')->name('manufacturer-enable-disable');
        });

        Route::controller(SupplierController::class)->group(function () {
            Route::get('supplier-list', 'list')->name('supplier-list');
            Route::get('supplier-add', 'addSupplier')->name('supplier-add');
            Route::post('supplier-create', 'supplierCreate')->name('supplier-create');
            Route::get('supplier-view/{id}', 'supplierView')->name('supplier-view');
            Route::get('supplier-edit/{id}', 'supplierEdit')->name('supplier-edit');
            Route::delete('supplier-delete', 'deleteSupplier')->name('supplier-delete');
            Route::post('supplier-enable-disable','supplierEnableDisable')->name('supplier-enable-disable');
        });

        Route::controller(ParentProductController::class)->group(function () {
            Route::get('parent-product-list', 'list')->name('parent-product-list');
            Route::get('parent-product-add', 'addParentProduct')->name('parent-product-add');
            Route::get('parent-product-edit/{id}', 'parentProductEdit')->name('parent-product-edit');
            Route::post('parent-product-add-supplier', 'addParentProductSupplier')->name('parent-product-add-supplier');
            Route::post('data-sheet-create', 'addDataSheet')->name('data-sheet-create');
            Route::post('product-size-width-qty-create', 'addProductSizeWidthQty')->name('product-size-width-qty-create');
            Route::post('product-size-length-qty-create', 'addProductSizeLengthQty')->name('product-size-length-qty-create');
            Route::post('product-size-thickness-qty-create', 'addProductSizeThicknessQty')->name('product-size-thickness-qty-create');
            Route::post('spec-fastener-create', 'addSpecFastener')->name('spec-fastener-create');
            Route::post('spec-fastener-screw-create', 'addSpecFastenerScrew')->name('spec-fastener-screw-create');
            Route::post('spec-fastener-nail-create', 'addSpecFastenerNail')->name('spec-fastener-nail-create');
            Route::post('get-product-type-data', 'getProductTypeData')->name('get-product-type-data');
            Route::post('parent-product-type-create', 'parentProductTypeCreate')->name('parent-product-type-create');
            Route::post('parent-product-package-type-create', 'parentProductPackageTypeCreate')->name('parent-product-package-type-create');
            Route::post('main-sub-parent-product-type-create', 'mainSubParentProductTypeCreate')->name('main-sub-parent-product-type-create');
            Route::post('secondary-sub-parent-product-type-create', 'secondarySubParentProductTypeCreate')->name('secondary-sub-parent-product-type-create');
            Route::post('parent-product-create', 'parentProductCreate')->name('parent-product-create');
            Route::post('get-supplier-data', 'getSupplierData')->name('get-supplier-data');
            Route::post('get-supplier-view-data', 'getSupplierViewData')->name('get-supplier-view-data');
            Route::post('parent-product-enable-disable', 'parentProductEnableDisable')->name('parent-product-enable-disable');
            Route::delete('parent-product-delete', 'deleteParentProduct')->name('parent-product-delete');
            Route::get('parent-product-view/{id}', 'parentProductView')->name('parent-product-view');
            Route::post('update-default-data-sheet', 'updateDefaultDataSheet')->name('update-default-data-sheet');
        });
        
        Route::controller(ChildProductController::class)->group(function () {
            Route::get('child-product-list', 'listChildProduct')->name('child-product-list');
            Route::get('child-product-add', 'addChildProduct')->name('child-product-add');
            Route::post('child-product-store', 'storeChildProduct')->name('child-product-store');
            Route::get('child-product-edit/{id}', 'editChildProduct')->name('child-product-edit');
            Route::get('child-product-view/{id}', 'viewChildProduct')->name('child-product-view');
            Route::delete('child-product-delete', 'deleteChildProduct')->name('child-product-delete');
            Route::post('child-product-enable-disable','enableDisableChildProduct')->name('child-product-enable-disable');
            Route::post('child-product-add-supplier', 'addChildProductSupplier')->name('child-product-add-supplier');
            Route::post('child-product-color-create','createColorChildProduct')->name('child-product-color-create');
            Route::post('child-product-add-trowel', 'addChildProductTrowel')->name('child-product-add-trowel');
            Route::post('child-product-size-lbs-create','createProductSizeLbs')->name('child-product-size-lbs-create');
            Route::post('child-product-size-gallon-create','createProductSizeGallon')->name('child-product-size-gallon-create');
            Route::post('child-product-size-coverage-create','createProductSizeCoverage')->name('child-product-size-coverage-create');
            Route::post('child-product-overage-create','createProductOverage')->name('child-product-overage-create');
            Route::post('child-product-update-default-data-sheet', 'updateDefaultDataSheet')->name('child-product-update-default-data-sheet');
            Route::post('child-product-get-supplier-data', 'getSupplierData')->name('child-product-get-supplier-data');
            Route::post('child-product-get-supplier-view-data', 'getSupplierViewData')->name('child-product-get-supplier-view-data');

            
        });

        Route::controller(CmsController::class)->group(function () {
            Route::get('cms-page-list', 'CmsList')->name('cms-page-list');
            Route::get('cms-page-edit/{id}', 'CmsEdit')->name('cms-page-edit');
            Route::post('cms-page-update', 'CmsUpdate')->name('cms-page-update');
        });

        Route::controller(SubscriptionOrderController::class)->group(function () {
            Route::get('subscription-order-list', 'subscriptionOrderList')->name('subscription-order-list');
            Route::get('subscription-order-view/{id}', 'subscriptionOrderView')->name('subscription-order-view');
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login');
    return view('welcome');
});


Route::get('/wags', function () {
    // dd("call");
    return redirect()->route('admin.login');
});

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; {{date('Y')}} <a href="{{ route('admin.dashboard') }}">{{ config('app.name') }}</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
</footer>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}" />

  <title>TMW | @yield('page_title')</title>
  <link rel="icon" href="{{ asset('admin/dist/img/icon.png') }}" type="image/png">

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  {{-- <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"> --}}
  <!-- JQVMap -->
  {{-- <link rel="stylesheet" href="{{ asset('admin/plugins/jqvmap/jqvmap.min.css') }}"> --}}
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('admin/dist/css/adminlte.min.css') }}">

  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/daterangepicker/daterangepicker.css') }}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.min.css') }}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/toastr/toastr.min.css') }}">
  <!-- custom -->
  <link rel="stylesheet" href="{{ asset('admin/dist/css/custom.css') }}">
  @stack('customCSS')
</head>
<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
  <div class="data-loader"></div>

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('admin/dist/img/icon.png') }}" alt="TilingMyWay" height="100" width="100">
  </div>

  <!-- Navbar -->
  @include('admin/layouts/navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('admin/layouts/sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    @yield('content_header')
    @yield('content')

  </div>
  <!-- /.content-wrapper -->

  @include('admin.layouts.footer')


  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('admin/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('admin/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
  var APPNAME = "{{ config('app.name') }}";
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('admin/plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('admin/plugins/sparklines/sparkline.js') }}"></script>
<!-- JQVMap -->
{{-- <script src="{{ asset('admin/plugins/jqvmap/jquery.vmap.min.js') }}"></script>
<script src="{{ asset('admin/plugins/jqvmap/maps/jquery.vmap.usa.js') }}"></script> --}}
<!-- jQuery Knob Chart -->
<script src="{{ asset('admin/plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('admin/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('admin/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.js') }}"></script>
<!-- AdminLTE for demo purposes -->
{{-- <script src="{{ asset('admin/dist/js/demo.js') }}"></script> --}}
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{ asset('admin/dist/js/pages/dashboard.js') }}"></script> --}}
<!-- Toastr -->
<script src="{{ asset('admin/plugins/toastr/toastr.min.js') }}"></script>
<script src="{{ asset('admin/dist/js/custom.js') }}"></script>
@stack('scripts')
@stack('customJs')
</body>
</html>

resources/views/admin/layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav ">
        <li class="nav-item">
            <a class="nav-link slide-menu" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->

        <li class="nav-item ">
            <!-- <a class="nav-link" data-toggle="dropdown" href="#"> -->
            <div class=" dropdown nav-link d-flex" data-toggle="dropdown" href="#">
                    <div class="image mr-2">
                        <img src="{{ auth()->user()->profile_picture ? auth()->user()->profile_picture : asset('admin/dist/img/mycpp.png') }}" class="img-circle elevation-2" width="20px" height="20px" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block text-white">{{ auth()->user()->first_name.' '.auth()->user()->last_name }}</a>
                    </div>
                </div>
            </a>
            <div class="dropdown-menu  dropdown-menu-right">
                <a href="{{ route('admin.user-edit') }}"><span class="dropdown-item">Profile</span></a>
                <div class="dropdown-divider"></div>
                <a href="{{route('admin.logout')}}"><span class="dropdown-item">Logout</span></a>
                {{-- <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form> --}}
            </div>
        </li>
        <!-- <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
            <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li> -->
        <!-- <li class="nav-item dropdown">
            <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
                </a>
        </li> -->
    </ul>
</nav>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar elevation-4 sidebar-dark-light">
    <!-- Brand Logo -->
    <a href="{{route('admin.dashboard')}}" class="brand-link text-center navbar-light">
    <img src="{{ asset('admin/dist/img/icon.png') }}" alt="AdminLTE Logo" class="brand-image  elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-bold text-dark-full"> {{ auth()->user()->first_name.' '.auth()->user()->last_name }}  </span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column font-weight-bold text-white" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{route('admin.dashboard')}}" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{route('admin.user-list')}}" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-user"></i>
                        <p>User Management</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.manufacturer-list')}}" class="nav-link">
                        <i class="nav-icon fas fa-briefcase"></i>
                        <p>Manufacturer Management</p>
                    </a>
                </li>

                  <li class="nav-item">
                    <a href="{{route('admin.supplier-list')}}" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-truck"></i>
                        <p>Supplier Management</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.parent-product-list') }}" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-list"></i>
                        <p>Parent Product Management</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.child-product-list') }}" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-bars"></i>
                        <p>Child Product Management</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.cms-page-list') }}" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-book"></i>
                        <p>CMS Mangement</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.subscription-order-list') }}" class="nav-link">
                        <i class="nav-icon fas fa-light fa-crown"></i>
                        <p>Subscription Orders</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>